create database SKEY
go
USE SKEY
GO

CREATE TABLE INFO_USER
(
	ID_USER INT IDENTITY PRIMARY KEY,
	HASH_ VARCHAR(max),
	EMAIL_ VARCHAR(max)
)
GO
CREATE TABLE DATA_PASS
(
	ID_PASS INT IDENTITY PRIMARY KEY,
	URL_ VARCHAR(max),
	USER_ VARCHAR(max),
	PASS_ VARCHAR(max),
	ID_USER INT FOREIGN KEY(ID_USER) REFERENCES INFO_USER(ID_USER)

)
GO

select COUNT(*) from DATA_PASS where ID_PASS = 
go
select * FROM DATA_PASS 
where ID_PASS =1
and ID_USER = 0
select*from DATA_PASS